name: GLuaTest Runner

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - lua/**
  workflow_dispatch:

jobs:
  run-mainbranch-tests:
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main

  run-64bit-tests:
    uses: CFC-Servers/GLuaTest/.github/workflows/run_tests.yml@main
    with:
      branch: x86-64
